steps:
  # 步驟 1: 建構容器映像檔 (使用 _TAG 確保名稱有效)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/fei:${_TAG}' 
      - '.'
    id: Build

  # 步驟 2: 部署到 Cloud Run (修正 Secret 注入格式)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - run
      - deploy
      - fei
      - '--image'
      - 'gcr.io/$PROJECT_ID/fei:${_TAG}'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      # --- Secret 注入 (每個 Secret 獨立參數) ---
      - '--set-secrets=API_KEY=line-ai-api-key:latest'
      - '--set-secrets=kid=kid:latest'
      - '--set-secrets=GEMINI_API_KEY=gemini-api-key:latest'
    id: Deploy
    entrypoint: gcloud
images:
  - 'gcr.io/$PROJECT_ID/fei:${_TAG}'

# 變數宣告：允許我們在指令行傳遞 _TAG 變數
substitutions:
  _TAG: 'latest'
